version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:  my_vocabulary_book
      TZ: "Asia/Tokyo"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
